# \u6307\u5B9A\u8FD0\u884C\u7AEF\u53E3
server:
  port: 8101

# \u6307\u5B9A\u670D\u52A1\u540D\u79F0
spring:
  application:
    name: eureka-client

eureka:
  client:
    # \u6CE8\u518C\u5230Eureka\u7684\u6CE8\u518C\u4E2D\u5FC3
    register-with-eureka: true
    # \u83B7\u53D6\u6CE8\u518C\u5B9E\u4F8B\u5217\u8868
    fetch-registry: true
    service-url:
      # \u914D\u7F6E\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
      defaultZone: http://localhost:8001/eureka

