server:
  port: 8701

spring:
  application:
    name: feign-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

#\u5728Feign\u4E2D\u5F00\u542FHystrix
feign:
  hystrix:
    enabled: true

#\u65E5\u5FD7
logging:
  level:
    com.jourwon.springcloud.service: debug



