server:
  port: 8301

spring:
  application:
    name: ribbon-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

#user-service\u7684\u8C03\u7528\u8DEF\u5F84
service-url:
  user-service: http://user-service

